### ISSUE TITLE
Not sure how to move inside a file to get started for the study

### ISSUE THREAD

**Issue by alexkarasik** [ga-wdi-boston/node-nodeschool-study#118]
I set up the environment and followed the early directions of the study, but now I am inside learnyounode and can not get the first exercise started. 
I started with 
$ touch helloworld.js 
and then I wrote 
$ node helloworld.js
I know I am supposed to be inside of that file to work, but I am not sure how.
I tried writing the command:
console.log("Hello World");
And I am getting this error:
-bash: syntax error near unexpected token `"Hello World"'
But I assume that is just because I am trying to do a command from the directory since i am not inside the file I want to be in for this assignment.

**Comment by jrhorn424** [comment]
> I know I am supposed to be inside of that file to work, but I am not sure how.

How do you open a file to edit it?

**Comment by alexkarasik** [comment]
With the open command. I thought I was always working in terminal with node and misunderstood. got it now. Thanks.
