### ISSUE TITLE
learnyounode frustration

### ISSUE THREAD

**Issue by gabescarbrough** [ga-wdi-boston/node-nodeschool-study#89]
@gaand asked me to open this issue.

While working on learnyounode I found it to be frustrating. It seemed to assume a higher level of knowledge than we would have, and the Node documentation does not seem to aim to be digestible for new programmers as much as it seems to aim to appeal to those with more experience. 

learnyounode doesn't give necessary info, ask the question then give tips- it asks the question then gives tips without giving any real context. It wasn't until I looked up solutions to the problems that I somewhat understood the structure of a node function, which can make you feel obtuse since you didn't understand how to approach the problem before seeing someone else's answer.

As the docs make many references to technologies we haven't learned (such as UNIX) it can confuse a new programmer more as opposed to clarify when they are looking for a bit of context or a simple explanation.

Once we covered Node in class it began to make more sense, so perhaps it would be better to at least briefly go over what Node is, why it is used, and the basics of its structure before assigning nodeschool. As well as saying up front that it is expected for it to be challenging.

**Comment by gaand** [comment]
@gabescarbrough Thanks for this.  

@ga-wdi-boston/core I'd like to be involved in addressing this issue at the next iteration.  Thanks!

**Comment by BenGitsCode** [comment]
@gaand I'd like to discuss this with you tomorrow, 12/4 if possible.

**Comment by gaand** [comment]
12/5?

**Comment by BenGitsCode** [comment]
Ah, yes. The date of 'tomorrow' is usually an increment higher than today, not the same. My mistake 😪 🐀 .

**Comment by neugierige** [comment]
@BenGitsCode and I have discussed that for WDI015, when we assign this study, we will announce that this study is definitely a challenge, emphasize that the requirement is completeness not accuracy, and that things will become much clearer after the node-api talk. 

Ok to close?

**Comment by gaand** [comment]
I think I'd like to have the chat with Ben first.

**Comment by BenGitsCode** [comment]
@gaand let's chat this week when you're free. I have thoughts on this issue for future iterations.

**Comment by benjimelito** [comment]
Any update on this issue?
